### ISSUE TITLE
What did you do as a hacker at backpack?

### ISSUE THREAD

**Issue by nawazm92** [torifat/ama#2]
Somewhere I've seen your job as "Hacker @ Backpack". So need to know what did you do there. Was that anything relates with programming stuff?

Also, if you could give some tips for front-end developers, would be graceful!

**Comment by torifat** [comment]
"Hacker @ Backpack" - It's just a cool way of saying that we don't have any hierarchy. They were already using React. So, I mostly helped them build their front-end stack around it. I tried to introduce build system, state-management, etc.

> could give some tips for front-end developers

Keep yourself up to date with the ongoing innovation. But don't follow the hype. Always justify your choice. Don't use something just because Mr. X or Company Y is using it.
